CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    telegram_id INTEGER UNIQUE NOT NULL,
    pet_type TEXT NULL,
    difficulty INTEGER NOT NULL DEFAULT 1,
    created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS pet_status (
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    hunger INTEGER NOT NULL DEFAULT 1,
    thirst INTEGER NOT NULL DEFAULT 1,
    hygiene INTEGER NOT NULL DEFAULT 1,
    energy INTEGER NOT NULL DEFAULT 1,
    mood INTEGER NOT NULL DEFAULT 1,
    health INTEGER NOT NULL DEFAULT 1,
    updated_at INTEGER NOT NULL,
    is_dead INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    active INTEGER NOT NULL DEFAULT 1,
    difficulty INTEGER NOT NULL,
    task_index INTEGER NOT NULL DEFAULT 0,
    awaiting_care INTEGER NOT NULL DEFAULT 0,
    care_json TEXT NULL,
    started_at INTEGER NOT NULL,
    ended_at INTEGER NULL
);
